apiVersion: apps/v1
kind: Deployment
metadata:
  name: k3s-hello-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k3s-hello
  template:
    metadata:
      labels:
        app: k3s-hello
    spec:
      containers:
      - name: app
        image: k3s-hello-app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
